name: Check Markdown links

on: 
  push:
  pull_request:
  schedule:
    - cron: '24 23 15 * *'

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
